site_name: MaskdDev Docs
copyright: Copyright &copy; 2024 Adithya Udupa
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.footer

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MaskdDev/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/H2C7rem29c/

nav:
  - Home: index.md
  - WriterStats:
    - Home: writerstats/index.md
    - Terms:
      - Terms of Service: writerstats/legal/index.md
      - Privacy Policy: writerstats/legal/privacy.md
    - Roadmap: https://maskddev.notion.site/0b3c27630c8a43cea763d3a391d169de?v=ed761e14b48d4896b68617e051ffbd07&pvs=4

  - Veatrix:
    - Home: veatrix/index.md
    - List of Commands: veatrix/commands.md
    - Terms:
      - Terms of Service: veatrix/legal/index.md
      - Privacy Policy: veatrix/legal/privacy.md
    
  - Writer-Bot:
    - Terms:
      - Terms of Servise: writerbot/legal/index.md
      - Privacy Policy: writerbot/legal/privacy.md

  - The Sprongler:
    - Terms:
      - Terms of Servise: sprongler/legal/index.md
      - Privacy Policy: sprongler/legal/privacy.md
    
plugins:
  - redirects:
      redirect_maps:
          'writerstats/roadmap.md': https://maskddev.notion.site/0b3c27630c8a43cea763d3a391d169de?v=ed761e14b48d4896b68617e051ffbd07&pvs=4